version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - laravel

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8002:80"
    depends_on:
      - php-fpm
    networks:
      - laravel

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:alpine
    networks:
      - laravel

  frankenphp:
    build:
      context: .
      dockerfile: .docker/franken/Dockerfile
    entrypoint: php artisan octane:frankenphp --workers=4
    volumes:
      - .:/app
    networks:
      - laravel
    ports:
      - "8004:8000"

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
